var tipuesearch = {"pages": [

     //Home Page

     {"title": "Florastor - Daily Probiotic Supplement", "text": "Are you Biotic? Florastor<sup>®</sup> is a daily* probiotic that complements your active lifestyle by supporting a healthy digestive balance.1 When you have healthy digestion, you have greater freedom to engage in the activities you love. ", "tags": "", "url": "https://florastor.ca/"},
     {"title": "Florastor - Daily Probiotic Supplement", "text": "Whether you’re training for a marathon or pushing your mind and body to new limits on the yoga mat, Florastor helps to keep you driven, confident, and strong. This is what it means to be Biotic.", "tags": "", "url": "https://florastor.ca/"},
     {"title": "Are You Biotic?", "text": "...Florastor helps to keep you driven, confident, and strong. This is what it means to be Biotic.", "tags": "biotic", "url": "https://florastor.ca/"},
     {"title": "New Look, Same Trusted Probiotic", "text": "New Packaging coming soon to your local retail pharmacy; Where to Buy; Learn More; Download Coupons;", "tags": "new", "url": "https://florastor.ca/"},

     //Coupons Page

     {"title": "Florastor Coupons", "text": "Download your Florastor<sup>®</sup> coupon by clicking on the link below. After entering your phone number, you will receive a one-time code on your mobile device. Use the code to access and print your Florastor coupon from Coupons.com.", "tags": "coupon discount download print", "url": "https://florastor.ca/coupons/"},

     //Purchase Page: Add Store location tags

     {"title": "Purchase Florastor: Store Locator", "text": "Find Florastor at Your Local Store; Find Florastor From Online: Get Florastor<sup>®</sup> delivered directly to your home by purchasing online from Well.ca. Florastor doesn't require refrigeration which means the probiotic properties of our active ingredient will be preserved en route to your home.", "tags": "online store purchase buy where", "url": "https://florastor.ca/purchase"},

     //FAQs

     {"title": "Frequently Asked Questions", "text": "Find all the answers to your frequently asked questions about Florastor here. For more information, visit our about page or contact us.", "tags": "faq frequently asked questions", "url": "https://florastor.ca/faqs/"},
     {"title": "What Is A Probiotic?", "text": "Health Canada and the World Health Organization define probiotics as \"live microorganisms which, when administered in adequate amounts, confer a health benefit to the host.\"8 These microorganisms include both bacteria and yeast-based cells, which interact with the body differently based on the specific strain of probiotic.", "tags": "what is probiotic microorganisms yeast", "url": "https://florastor.ca/faqs/"},
     {"title": "Why is Florastor<sup>®</sup> a Unique Probiotic?", "text": "Florastor is unique because it is the only probiotic that features the specific strain, Saccharomyces boulardii lyo CNCM I-745, a friendly yeast found naturally on the skin of lychees and mangosteens (tropical fruits). Most of the other probiotics you'll find on the market are bacterial probiotics that are either in capsule form or in foods such as yogurt. Florastor offers unique advantages over many bacterial probiotics for the relief of diarrhea from antibiotics, intestinal infection, or to promote a favorable gut flora for intestinal health.1,2,3,4,5,6", "tags": "unique probiotic saccharomyces boulardii", "url": "https://florastor.ca/faqs/"},
     {"title": "What is Florastor suggested for?", "text": "Florastor is a probiotic supplement intended for the effective relief of diarrhea and to promote the body's own natural gut flora.1,4,5,6 Anyone's gut flora can become upset and vulnerable—whether from the daily flow of an active lifestyle (travel, stress, diet), disruption from a prescribed antibiotic, a virus/infection, or nonspecific digestive issues. Florastor helps maintain peace in your intestinal tract to support intestinal health and harmony.1,2", "tags": "flora intestinal nutrients", "url": "https://florastor.ca/faqs/"},
     {"title": "What is the Florastor dosage recommended for diarrhea?", "text": "Take Florastor daily for up to one week for effective relief of diarrhea. If symptoms of diarrhea worsen or persist beyond three days, consult a healthcare practitioner. Antibiotic-Associated Diarrhea Adults: Take 2 capsules daily* (2 capsules can be taken 1-3 times a day, up to a maximum of 6 capsules per day) to help prevent antibiotic-associated diarrhea.4 Children: Take 1 sachet twice a day to help reduce the risk of antibiotic-associated diarrhea.5 Acute Infectious Diarrhea Adults: Take 2 capsules daily* (2 capsules can be taken 1-3 times a day, up to a maximum of 6 capsules per day) to help reduce symptoms related to acute infectious diarrhea.6 Children: Take 2 capsules twice a day to help treat acute infectious diarrhea.6", "tags": "diarrhea dosage recommended infectious", "url": "https://florastor.ca/faqs/"},
     {"title": "How should I take Florastor?", "text": "There are several ways to take Florastor: Swallow the capsule whole; Open the capsule or packet and sprinkle over semisolid food (applesauce, yogurt, etc.); Open the capsule or packet and dissolve the contents in liquid (water, juice, milk, formula, etc.);", "tags": "how to take eat", "url": "https://florastor.ca/faqs/"},
     {"title": "Is Florastor appropriate for kids?", "text": "Yes, FlorastorKids<sup>®</sup> is appropriate for children one year or older. FlorastorKids is available as a tutti-frutti-flavored powder sachet that can be mixed with a liquid or semisolid food.", "tags": "good for kids children florastor", "url": "https://florastor.ca/faqs/"},
     {"title": "What is the difference between Florastor and FlorastorKids?", "text": "The only difference is the tutti-frutti flavor in FlorastorKids. One Florastor capsule and one FlorastorKids powder sachet contain the same amount of Saccharomyces boulardii lyo (250mg).", "tags": "difference between florastor florastorkids kids vs", "url": "https://florastor.ca/faqs/"},
     {"title": "How is Florastor supplied?", "text": "Florastor is gluten-free and supplied in vegetarian capsules or powder sachets. Florastor and FlorastorKids can be found on the shelf near other digestive health products or behind the pharmacy counter in 10, 20, and 50 count packages.", "tags": "capsules sachets otc pharmacy", "url": "https://florastor.ca/faqs/"},
     {"title": "Do I need to refrigerate Florastor?", "text": "No, Florastor does not require refrigeration, making it travel-friendly. It is manufactured with a patented lyophilization process, similar to freeze-drying. This allows for storage at room temperature to guarantee an optimal level of living cells. Do not refrigerate Florastor after opening as this could expose the cells to moisture and compromise its three-year shelf life.", "tags": "refrigerate refrigeration require need shelf life", "url": "https://florastor.ca/faqs/"},
     {"title": "How long does it take for Florastor to work?", "text": "Within approximately 30 minutes after ingestion, each Florastor capsule dissolves in the stomach, allowing the yeast cells to help keep your intestinal tract on track. Florastor can only benefit you during days of use. Florastor is naturally eliminated through the digestive tract and is undetectable within five days after last consumption.7", "tags": "how long to work", "url": "https://florastor.ca/faqs/"},
     {"title": "If I am taking an antibiotic, can I take Florastor too?", "text": "Yes, because Florastor is a yeast-based probiotic, it is not compromised by antibiotics. Antibiotics can kill bad and good bacteria, including many bacterial probiotics you’ll find in capsule form or in foods such as yogurt.", "tags": "antibiotic", "url": "https://florastor.ca/faqs/"},
     {"title": "Are there any known adverse reactions?", "text": "Rarely: Flatulence, constipation, thirst, pruritus, rash, angioedema. Very rarely: Anaphylactic reaction. Do not use if you have hypersensitivity to any component of the product (especially allergy to yeast) or if you have a central venous catheter. May contain traces of soy.", "tags": "adverse reactions side effects", "url": "https://florastor.ca/faqs/"},
     {"title": "Can Florastor cause a vaginal yeast infection?", "text": "No, Florastor does not cause or exacerbate a vaginal yeast infection of Candida origin. Taken by mouth, Florastor transits through the gastrointestinal tract and does not pass through the urinary or genital system.", "tags": "vaginal yeast infection", "url": "https://florastor.ca/faqs/"},
     {"title": "What if I am nursing or pregnant?", "text": "In the absence of reliable animal teratogenesis data, Biocodex advises women who are pregnant or nursing to check with their healthcare practitioner before using Florastor.", "tags": "nursing pregnant", "url": "https://florastor.ca/faqs/"},
     {"title": "How long can I use Florastor?", "text": "Recommended duration of use for antibiotic-associated diarrhea and acute infectious diarrhea is up to one week. However, long-term use of Florastor has not been associated with complications. After repeated oral doses, Florastor transits through the digestive tract attaining steady-state levels that are maintained throughout the administration period.3 Florastor is no longer present in stools two to five days after discontinuation of treatment.7", "tags": "how long term use", "url": "https://florastor.ca/faqs/"},

     //About Page 

     {"title": "What is Florastor?", "text": "Florastor<sup>®</sup> is a daily* probiotic supplement that supports healthy digestion by promoting favorable gut flora.1 As the only probiotic with Saccharomyces boulardii lyo CNCM I-745, a unique probiotic strain with over 60 years of use and research worldwide, Florastor offers many advantages to supporting your digestive health.", "tags": "what is florastor probiotic about page", "url": "https://florastor.ca/about/"},
     {"title": "About Florastor", "text": "As the only probiotic with Saccharomyces boulardii lyo CNCM I-745, a unique probiotic strain with over 60 years of use and research worldwide, Florastor offers many advantages to supporting your digestive health.", "tags": "what is florastor", "url": "https://florastor.ca/about/"},
     {"title": "What Are Probiotics?", "text": "Health Canada and the World Health Organization define probiotics as \"live microorganisms which, when administered in adequate amounts, confer a health benefit to the host.\"8 The human body hosts approximately 100 trillion microorganisms, also known as microbiota or microflora. When the flora in your digestive system becomes imbalanced due to antibiotics, viruses, or unfriendly bacteria, it can lead to abdominal discomfort and diarrhea. Probiotics help balance your gut flora to support a healthy digestive system.", "tags": "what are probiotics", "url": "https://florastor.ca/about/"},
     {"title": "What Makes Florastor Unique?", "text": "Florastor is the ONLY probiotic supplement with Saccharomyces boulardii lyo CNCM I-745, a unique probiotic strain naturally resistant to ALL antibiotics.3", "tags": "", "url": "https://florastor.ca/about/"},
     
     {"title": "Help prevent antibiotic-associated diarrhea in adults4", "text": "When taken at recommended levels, Florastor has been shown to do the following: Help prevent antibiotic-associated diarrhea in adults4", "tags": "diarrhea antibiotic antibiotic-associated prevent", "url": "https://florastor.ca/about/"},
     {"title": "Help reduce the risk of antibiotic-associated diarrhea in children5", "text": "When taken at recommended levels, Florastor has been shown to do the following: Help reduce the risk of antibiotic-associated diarrhea in children5", "tags": "reduce risk antibiotic-associated diarrhea children", "url": "https://florastor.ca/about/"},
     {"title": "Help reduce the symptoms related to acute infectious diarrhea in adults6", "text": "When taken at recommended levels, Florastor has been shown to do the following: Help reduce the symptoms related to acute infectious diarrhea in adults6", "tags": "acute infectious diarrhea adults", "url": "https://florastor.ca/about/"},
     {"title": "Help treat acute infectious diarrhea in children6", "text": "When taken at recommended levels, Florastor has been shown to do the following: Help treat acute infectious diarrhea in children6", "tags": "acute infectious diarrhea children", "url": "https://florastor.ca/about/"},
     {"title": "Promote a favorable gut flora for the support of gastrointestinal health1", "text": "When taken at recommended levels, Florastor has been shown to do the following: Promote a favorable gut flora for the support of gastrointestinal health1", "tags": "favorable gut flora gastrointestinal health", "url": "https://florastor.ca/about/"},

     {"title": "The History of Florastor", "text": "While traveling in Indochina in the early 1920’s, Henri Boulard, a French microbiologist, noticed the locals drinking a special tea—made from lychee and mangosteen—to help with digestion. Fascinated by the healing properties of these two tropical fruits, Boulard conducted further research and discovered the active ingredient to be what he later called Saccharomyces boulardii.S. boulardii was first introduced to the market in 1953 by the French pharmaceutical company Biocodex. Since then, it has become available in over 100 countries making it the #1 probiotic worldwide.9 Florastor is the only probiotic in North America to contain S. boulardii lyo CNCM I- 745. With over 60 years of use and research, Florastor is the trusted probiotic of choice by families around the world.", "tags": "history", "url": "https://florastor.ca/about/"},
     {"title": "Saccharomyces boulardii", "text": "Boulard conducted further research and discovered the active ingredient to be what he later called Saccharomyces boulardii.S. boulardii was first introduced to the market in 1953 by the French pharmaceutical company Biocodex. Since then, it has become available in over 100 countries making it the #1 probiotic worldwide.9", "tags": "saccharomyces boulardii lyo", "url": "https://florastor.ca/about/"},
     
     //Products Page

     {"title": "Florastor Daily Probiotics", "text": "Florastor is gluten-free and available in vegetarian capsules or powder sachets appropriate for children 1 year and older. Florastor is also convenient for active lifestyles because it does not require refrigeration and has a three-year shelf life. When taken as recommended, Florastor promotes favorable gut flora to support a healthy digestive balance.1", "tags": "products box boxes", "url": "https://florastor.ca/products/"},
     {"title": "Florastor Capsules", "text": "Florastor capsules are easy to take wherever you go. Swallow the capsules whole or mix the powder into your favorite food or beverage. Each capsule contains 250mg of our unique probiotic strain, Saccharomyces boulardii lyo CNCM I-745.", "tags": "products capsule florastor 10 20 50 box boxes", "url": "https://florastor.ca/products/"},
     {"title": "FlorastorKids", "text": "FlorastorKids<sup>&reg;</sup> helps your children with healthy digestion while keeping their taste buds happy. Each powder sachet contains the same dose as one Florastor capsule and is naturally sweetened with tutti-frutti flavoring. FlorastorKids is also a great alternative for adults with difficulty swallowing capsules.", "tags": "florastor kids children 20 box boxes products", "url": "https://florastor.ca/products/"},
     {"title": "FlorastorMax", "text": "FlorastorMax<sup>&reg;</sup> provides an extra-strength serving of your daily probiotic needs in one convenient sachet. Each sachet contains 500 mg of our unique probiotic strain and is naturally sweetened with vanilla flavoring.", "tags": "florastor max sachets 30 box boxes products", "url": "https://florastor.ca/products/"},

  

     {"title": "", "text": "", "tags": "", "url": "https://florastor.ca/"}
]};


