<?php /* Template Name: Terms */ ?>

<?php get_header('terms'); ?>
<?php get_header(); ?>

    <div class="container">
    <div class="col-sm-12">
    <br><br>
	<em>Last Updated: January 31, 2017</em>
	<br><br>
	<h1 id="header-img">TERMS OF SERVICE</h1>

	<br><br>

	<p style="font-size: 1.1em;">Please read these Terms of Service (the “Agreement”) carefully. Your use of the Site (as defined below) constitutes your consent to this Agreement.</p>
	<br>
	<p style="font-size: 1.1em;">This Agreement is between you and Biocodex Canada, Inc. (“Company” or “we” or “us”) concerning your use of (including any access to) the Florastor site currently located at www.florastor.ca (together with any materials and services available therein, and successor site(s) thereto, the “Site”). This Agreement hereby incorporates by this reference any additional terms and conditions posted by Company through the Site, or otherwise made available to you by Company.</p>

	<p style="font-size: 1.1em;">By using the Site, you affirm that you are of legal age to enter into this Agreement.  or, if you are not, that you have obtained parental or guardian consent to enter into this Agreement.</p>
	<br>
	<p style="font-size: 1.1em;">This Agreement contains a mandatory individual arbitration and class action/jury trial waiver provision. To the extent it applies, this provision requires the use of arbitration on an individual basis to resolve disputes, rather than jury trial or class actions. </p>
	<p style="font-size: 1.1em;">If you are an individual accessing or using the Site on behalf of, or for the benefit of, any corporation, partnership or other entity with which you are associated (an “Organization”), then you are agreeing to this Agreement on behalf of yourself and such Organization, and you represent and warrant that you have the legal authority to bind such Organization to this Agreement. <br>References to “you” and “your” in this Agreement will refer to both the individual using the Site and to any such Organization.</p><br>

	<h4 style="font-weight: 900; font-size: 1.3em;">1.  This Site Does Not Provide Medical Advice.</h4>
	<p style="font-size: 1.1em;">Information provided through the Site and the content of the Site, such as text, information, graphics, audio, video, images, and other material contained on the Site (collectively, the “Content”) are for informational purposes only, and they neither constitute nor are intended to be a substitute for medical advice, diagnosis, or treatment. The Content may not be complete and does not cover all health or medical issues. Therefore, never use or rely on any information on the Site in place of a consultation with your doctor or other health care provider. No one that you contact through our Site is authorized to provide medical or other professional advice through the Site. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical health condition. Never disregard professional medical or health advice or delay in seeking it because of something you have learned through or read on the Site. If you think you may have a medical or health emergency, call your doctor or 911 immediately. <em>Reliance on any information provided by us, our employees, others appearing on the Site at our invitation, or other visitors to the Site is solely at your own risk.</em> We do not recommend self-management of health problems nor do we endorse any particular type of medical or health treatment. The Content provided by the Site is not a substitute for medical advice and nothing contained on the Site or in a response to your inquiries or questionnaires is intended to be a medical diagnosis or treatment plan. If you suspect you have a medical or health problem, or if you have any health care related questions, please promptly call or see your physician or other health care provider. We do not endorse the opinions or recommendations posted or sent by users shared through the Site and we disclaim all responsibility and liability in connection with all such information. Note that information on this Site regarding Florastor products is provided as a courtesy to consumers and their healthcare providers. We are not advocating any indication, dosage, or other claim that is not covered on the Product License for Florastor natural health products which bear an NPN and are authorized for sale by Health Canada. Please contact us at 1-877-356-7787 with any additional concerns or inquiries you may have regarding Florastor products. To report an adverse event with any Florastor product call toll-free: 1-877-356-7787.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">2. 	Changes.</h4> 
	<p style="font-size: 1.1em;">We may change this Agreement from time to time by notifying you of such changes by any reasonable means, including by posting a revised Agreement through the Site. Any such changes will not apply to any dispute between you and us arising prior to the date on which we posted the revised Agreement incorporating such changes, or otherwise notified you of such changes.</p>
	
	<p style="font-size: 1.1em;">Your use of the Site following any changes to this Agreement will constitute your acceptance of such changes. The “Last Updated” legend above indicates when this Agreement was last changed. We may, at any time and without liability, modify or discontinue all or part of the Site (including access to the Site via any third-party links); charge, modify or waive any fees required to use the Site; or offer opportunities to some or all Site users.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">3. 	Information Submitted Through the Site.</h4> 
	<p style="font-size: 1.1em;">Your submission of information through the Site is governed by Company’s Privacy Policy, located at <a href="/privacy/">florastor.ca/privacy</a> (the “Privacy Policy”). You represent and warrant that any information you provide in connection with the Site is and will remain accurate and complete, and that you will maintain and update such information as needed.  If you share any ideas, feedback, or suggestions for improvements or modifications to our products or services, or ideas for new products or services, they will each constitute Feedback that is licensed to us on an unrestricted basis in accordance with Section 9 below. </p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">4. 	Jurisdictional Issues.</h4> 
	<p style="font-size: 1.1em;">The Site is controlled or operated (or both) from the United States, and is not intended to subject Company to any non-U.S. or non-Canadian jurisdiction or law. The Site may not be appropriate or available for use in some non-U.S. or non-Canadian jurisdictions. Any use of the Site is at your own risk, and you must comply with all applicable laws, rules and regulations in doing so. We may limit the Site’s availability at any time, in whole or in part, to any person, geographic area or jurisdiction that we choose.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">5. 	Rules of Conduct.</h4> 
	<p style="font-size: 1.1em;">In connection with the Site, you must not:
	<ul style="font-size: 1.1em;">
	<li>Post, transmit or otherwise make available through or in connection with the Site any materials that are or may be: (a) threatening, harassing, degrading, hateful or intimidating, or otherwise fail to respect the rights and dignity of others; (b) defamatory, libelous, fraudulent or otherwise tortious; (c) obscene, indecent, pornographic or otherwise objectionable; or (d) protected by copyright, trademark, trade secret, right of publicity or privacy or any other proprietary right, without the express prior written consent of the applicable owner.</li>
	<li>Post, transmit or otherwise make available through or in connection with the Site any virus, worm, Trojan horse, Easter egg, time bomb, spyware or other computer code, file or program that is or is potentially harmful or invasive or intended to damage or hijack the operation of, or to monitor the use of, any hardware, software or equipment (each, a “Virus”).</li>
	<li>Use the Site for any commercial purpose, or for any purpose that is fraudulent or otherwise tortious or unlawful.</li>
	<li>Harvest or collect information about users of the Site.</li>
	<li>Interfere with or disrupt the operation of the Site or the servers or networks used to make the Site available, including by hacking or defacing any portion of the Site; or violate any requirement, procedure or policy of such servers or networks.</li>
	<li>Restrict or inhibit any other person from using the Site.</li>
	<li>Reproduce, modify, adapt, translate, create derivative works of, sell, rent, lease, loan, timeshare, distribute or otherwise exploit any portion of (or any use of) the Site except as expressly authorized herein, without Company’s express prior written consent.</li>
	<li>Reverse engineer, decompile or disassemble any portion of the Site, except where such restriction is expressly prohibited by applicable law.</li>
	<li>Remove any copyright, trademark or other proprietary rights notice from the Site.</li>
	<li>Frame or mirror any portion of the Site, or otherwise incorporate any portion of the Site into any product or service, without Company’s express prior written consent.</li>
	<li>Systematically download and store Site Content.</li>
	<li>Use any robot, spider, site search/retrieval application or other manual or automatic device to retrieve, index, “scrape,” “data mine” or otherwise gather Site Content, or reproduce or circumvent the navigational structure or presentation of the Site, without Company’s express prior written consent. Notwithstanding the foregoing, and subject to compliance with any instructions posted in the robots.txt file located in the Site’s root directory, Company grants to the operators of public search engines permission to use spiders to copy materials from the Site for the sole purpose of (and solely to the extent necessary for) creating publicly available, searchable indices of such materials, but not caches or archives of such materials. Company reserves the right to revoke such permission either generally or in specific cases, at any time and without notice.</li>
	</ul></p>
	<p style="font-size: 1.1em;">You are responsible for obtaining, maintaining and paying for all hardware and all telecommunications and other services needed to use the Site.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">6. 	Products.</h4> 
	<p style="font-size: 1.1em;">The Site may make available listings, descriptions and images of goods or services or related coupons or discounts (collectively, “<u>Products</u>”), as well as references and links to Products. Such Products may be made available by Company or by third parties, and may be made available for any purpose, including general information purposes. The availability through the Site of any listing, description or image of a Product does not imply our endorsement of such Product or affiliation with the provider of such Product unless it is identified on the Site as developed, manufactured and sold by us. We make no representations as to the completeness, accuracy, reliability, validity or timeliness of such listings, descriptions or images (including any features, specifications and prices contained therein). Such information and the availability of any Product (including the validity of any coupon or discount) are subject to change at any time without notice. Certain weights, measures and similar descriptions are approximate and are for convenience only. We make reasonable efforts to accurately display the attributes of Products, including the applicable colors, however the actual colors you see will depend on your computer system, and we cannot guarantee that your computer will accurately display such colors. It is your responsibility to ascertain and obey all applicable local, state, provincial, federal and foreign laws (including minimum age requirements) regarding the possession, use and sale of any Product. </p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">7. 	Registration; User Names and Passwords.</h4> 
	<p style="font-size: 1.1em;">You may need to register to use all or part of the Site. We may reject, or require that you change, any user name, password or other information that you provide to us in registering. Your user name and password are for your personal use only and should be kept confidential; you, and not Company, are responsible for any use or misuse of your user name or password, and you must promptly notify us of any confidentiality breach or unauthorized use of your user name or password, or your Site account.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">8. 	Profiles and Forums.</h4> 
	<p style="font-size: 1.1em;">Site visitors may make available certain materials (each, a “<u>Submission</u>”) through or in connection with the Site, including on profile pages or on the Site’s interactive services, such as message boards and other forums, and chatting, commenting and other messaging functionality. Company has no control over and is not responsible for any use or misuse (including any distribution) by any third party of Submissions. If you choose to make any of your personally identifiable or other information publicly available through the Site, you do so at your own risk.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">9. 	License.</h4> 
	<p style="font-size: 1.1em;">For purposes of clarity, you retain ownership of your Submissions. For each Submission, you hereby grant to us a worldwide, royalty-free, fully paid-up, non-exclusive, perpetual, irrevocable, transferable and fully sublicensable (through multiple tiers) license, without additional consideration to you or any third party, to reproduce, distribute, perform and display (publicly or otherwise), create derivative works of, adapt, modify and otherwise use, analyze, make, use, sell, offer for sale, import, and otherwise exploit such Submission, in any format or media now known or hereafter developed, and for any purpose (including promotional purposes, such as testimonials).</p>
	<p style="font-size: 1.1em;">In addition, if you provide to us any ideas, proposals, suggestions or other materials including but not limited to suggestions for improvements or modifications to our products or services, or ideas for new products or services (collectively, “<u>Feedback</u>”), whether related to the Site or otherwise, such Feedback will be deemed a Submission, and you hereby acknowledge and agree that such Feedback is not confidential, and that your provision of such Feedback is gratuitous, unsolicited and without restriction, and does not place Company under any fiduciary or other obligation.</p>
	<p style="font-size: 1.1em;">You represent and warrant that you have all rights necessary to grant the licenses granted in this section, and that your Submissions, and your provision thereof through and in connection with the Site, are complete and accurate, and are not fraudulent, tortious or otherwise in violation of any applicable law or any right of any third party. You further irrevocably waive any “moral rights” or other rights with respect to attribution of authorship or integrity of materials regarding each Submission that you may have under any applicable law under any legal theory.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">10. 	Monitoring.</h4> 
	<p style="font-size: 1.1em;">We may (but have no obligation to) monitor, evaluate, alter or remove Submissions before or after they appear on the Site, or analyze your access to or use of the Site. We may disclose information regarding your access to and use of the Site, and the circumstances surrounding such access and use, in accordance with our Privacy Policy.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">11. 	Your Limited Rights.</h4>
	<p style="font-size: 1.1em;">Subject to your compliance with this Agreement, and solely for so long as you are permitted by Company to use the Site, you may view one (1) copy of any portion of the Site to which we provide you access under this Agreement, on any single device, solely for your personal, non-commercial use.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">12. 	Company’s Proprietary Rights.</h4> 
	<p style="font-size: 1.1em;">We and our suppliers own the Site, which is protected by proprietary rights and laws. The Site may include our, or our licensors’, trade names, trademarks and service marks, including Florator, FlorastorKids, FlorastorMax and any associated logos of the foregoing. All trade names, trademarks, service marks and logos on the Site not owned by us are the property of their respective owners. You may not use our trade names, trademarks, service marks or logos in connection with any product or service that is not ours, or in any manner that is likely to cause confusion. Nothing contained on the Site should be construed as granting any right to use any trade names, trademarks, service marks or logos without the express prior written consent of the owner.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">13. 	Third Party Materials; Links.</h4> 
	<p style="font-size: 1.1em;">Certain Site functionality may make available access to information, products, services and other materials made available by third parties, including Submissions (“<u>Third Party Materials</u>”), or allow for the routing or transmission of such Third Party Materials, including via links. By using such functionality, you are directing us to access, route and transmit to you the applicable Third Party Materials.</p>
	<p style="font-size: 1.1em;">We neither control nor endorse, nor are we responsible for, any Third Party Materials, including the accuracy, validity, timeliness, completeness, reliability, integrity, quality, legality, usefulness or safety of Third Party Materials, or any intellectual property rights therein. Certain Third Party Materials may, among other things, be inaccurate, misleading or deceptive. Nothing in this Agreement shall be deemed to be a representation or warranty by Company with respect to any Third Party Materials. We have no obligation to monitor Third Party Materials, and we may block or disable access to any Third Party Materials (in whole or part) through the Site at any time. In addition, the availability of any Third Party Materials through the Site does not imply our endorsement of, or our affiliation with, any provider of such Third Party Materials, nor does such availability create any legal relationship between you and any such provider.</p>	
	<p style="font-size: 1.1em;">Your use of Third Party Materials is at your own risk and is subject to any additional terms, conditions and policies applicable to such Third Party Materials (such as terms of service or privacy policies of the providers of such Third Party Materials).</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">14. 	Promotions.</h4> 
	<p style="font-size: 1.1em;">Any sweepstakes, contests, raffles, surveys, games or similar promotions (collectively, “<u>Promotions</u>”) made available through the Site may be governed by rules that are separate from this Agreement. If you participate in any Promotions, please review the applicable rules as well as our Privacy Policy. If the rules for a Promotion conflict with this Agreement, the Promotion rules will govern.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">15. 	Disclaimer of Warranties.</h4> 
	<p style="font-size: 1.1em;">Some jurisdictions, including Quebec, may not allow the disclaimers contained below. only the disclaimers which are lawful in your jurisdiction, and to the maximum extent permitted by law, will apply to you and our liability will be limited to the maximum extent permitted by law. you may have additional rights under applicable laws.</p>
	<p style="font-size: 1.1em;">The Site and any Products and Third Party Materials are made available to you on an “As Is,” “Where Is” and “Where Available” basis, without any warranties or conditions of any kind, whether legal, express, implied or statutory. Company disclaims all warranties and conditions with respect to the Site and any Products and Third Party Materials to the fullest extent permissible under applicable law, including the warranties of merchantability, quality and fitness for a particular purpose, non-infringement and title, whether arising from statute, course of dealing, usage of trade or otherwise. All disclaimers of any kind (including in this section and elsewhere in this Agreement) are made on behalf of both Company and its affiliates and their respective investors, shareholders, directors, officers, employees, affiliates, mandataries, agents, representatives, licensors, suppliers and service providers (collectively, the “Affiliated Entities”), and their respective successors and assigns.</p>
	<p style="font-size: 1.1em;">While we try to maintain the timeliness, integrity and security of the Site, we do not guarantee that the Site is or will remain updated, complete, correct or secure, or that access to the Site will be uninterrupted. The Site may include inaccuracies and errors. Additionally, third parties may make unauthorized alterations to the Site. If you become aware of any such alteration, contact us at info-florastor@biocodex.com with a description of such alteration and its location on the Site.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">16. 	Limitation of Liability.</h4>
	<p style="font-size: 1.1em;">The laws of certain jurisdictions, including Quebec, may not allow the exclusion or limitation of certain liabilities. if and solely to the extent that these laws apply to you, some or all of the exclusions or limitations below may not apply to you, and you may have additional rights.</p>
	<p style="font-size: 1.1em;">Except to the extent prohibited by law, in no event will Company or its Affiliated entities, and their respective successors and assigns, be liable for any indirect, incidental, consequential, special, exemplary, punitive, direct or any other damages of any kind, under any contract, tort (including negligence), strict liability, civil liability or other theory, including damages for loss of profits, use or data, loss of other intangibles, loss of security of Submissions (including unauthorized interception by third parties of any Submissions), even if advised in advance of the possibility of such damages or losses. Without limiting the foregoing, Company or its Affiliated entities, and their respective successors and assigns, will not be liable for damages or loss of any kind which arises out of or is in any way connected with your use of or inability to use the Site or any content or from any Products or Third Party Materials, including from any Virus that may be transmitted in connection therewith. Your sole and exclusive remedy for dissatisfaction with the Site or any Products or Third Party Materials is to stop using the Site. All limitations of liability of any kind (including in this section and elsewhere in this Agreement) are made on behalf of both Company and the Affiliated Entities, and their respective successors and assigns.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">17. 	Indemnity.</h4> 
	<p style="font-size: 1.1em;">Except to the extent prohibited under applicable law, you agree to defend, indemnify and hold harmless Company and the Affiliated Entities, and their respective successors and assigns, from and against all claims, liabilities, damages, judgments, awards, losses, costs, expenses and fees (including legal fees) arising out of or relating to (a) your use of, or activities in connection with, the Site (including all Submissions); and (b) any violation or alleged violation of this Agreement by you.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">18. 	Termination.</h4> 
	<p style="font-size: 1.1em;">This Agreement is effective until terminated. Company may terminate or suspend your use of the Site at any time and without prior notice, for any or no reason, including if Company believes that you have violated or acted inconsistently with the letter or spirit of this Agreement. Upon any such termination or suspension, your right to use the Site will immediately cease, and Company may, without liability to you or any third party, immediately deactivate or delete your user name, password and account, and all associated materials, without any obligation to provide any further access to such materials. Sections 1, 3–10, and 12–23 shall survive any expiration or termination of this Agreement.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">19. 	Class Action/Jury Trial Waiver. </h4>
	<p style="font-size: 1.1em;">Some jurisdictions, including Quebec, may not allow a mandatory arbitration or waiver of class action/jury trial in certain circumstances so this section may not apply to you.</p>	
	<p style="font-size: 1.1em;">All claims arising out of or related to this agreement must be brought in the parties’ individual capacity, and not as a plaintiff or class member in any purported class action, collective action, private attorney general action or other representative proceeding. This waiver applies to class arbitration, and, unless the parties agree otherwise, the arbitrator may not consolidate more than one person’s claims. You agree that, by entering into this agreement, you and we are each waiving the right to a trial by jury or to participate in a class action, collective action, private attorney general action, or other representative proceeding of any kind. You can opt out of this class action waiver by contacting Biocodex, Inc. 255 Shoreline Drive Suite 450, Redwood City, CA 94065 within 30 days after you first accept these Terms of Service, stating that you (include your first and last name) decline this class action waiver.</p>
	<br>	
	<h4 style="font-weight: 900; font-size: 1.3em;">20. 	Governing Law; Arbitration.</h4> 
	<p style="font-size: 1.1em;">This Agreement is and shall be governed by and construed under the laws of the State of California, U.S.A., without regard to its principles of conflicts of law, and regardless of your location, except where the laws of the jurisdiction where you reside requires that the laws of such jurisdiction to apply.</p>	
	<p style="font-size: 1.1em;">Except for disputes that qualify for small claims court and where applicable laws prohibit mandatory arbitration, all disputes arising out of or related to this agreement or any aspect of the relationship between you and us, whether based in contract, tort (including negligence), statute, fraud, misrepresentation or any other legal theory, will be resolved through final and binding arbitration before a neutral arbitrator instead of in a court by a judge or jury and you agree that we and you are each waiving the right to trial by a jury. You agree that any arbitration under this agreement will take place on an individual basis; class arbitrations and class actions are not permitted and you are agreeing to give up the ability to participate in a class action. The arbitration will be administered by JAMS under its Comprehensive Arbitration Rules and Procedures (“Comprehensive Rules”).  The Comprehensive Rules are available online at http://www.jamsadr.com/rules-comprehensive-arbitration/.  Any in-person appearances will be held at a location which is reasonably convenient to both parties with due consideration of their ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, such determination should be made by JAMS or by the arbitrator. The arbitrator’s decision will follow the terms of this Agreement and will be final and binding. The arbitrator will have authority to award temporary, interim or permanent injunctive relief or relief providing for specific performance of this Agreement, but only to the extent necessary to provide relief warranted by the individual claim before the arbitrator.  To reduce the time and expense of the arbitration, the arbitrator will not provide a statement of reasons for his or her award unless requested to do so by all parties. The award rendered by the arbitrator may be confirmed and enforced in any court having jurisdiction thereof.  An arbitration award and any judgement confirming it apply only to that specific case; it cannot be used in any other case expect to enforce the award itself. Notwithstanding any of the foregoing, nothing in this Agreement will preclude you from bringing issues to the attention of federal, provincial, state or local agencies and, if the law allows, they can seek relief against us for you.  Where the foregoing applies to you, you can opt out of this agreement to arbitrate by contacting Biocodex, Inc. 255 Shoreline Drive Suite 450, Redwood City, CA 94065 within 30 days after you first accept these Terms of Service, stating that you (include your first and last name) decline this arbitration agreement. </p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">21. 	Filtering.</h4> 
	<p style="font-size: 1.1em;">We hereby notify you that parental control protections (such as computer hardware, software or filtering services) are commercially available that may assist you in limiting access to material that is harmful to minors. Information identifying current providers of such protections is available from  <a href="https://en.wikipedia.org/wiki/Comparison_of_content-control_software_and_providers">https://en.wikipedia.org/wiki/Comparison_of_content-control_software_and_providers</a>. Please note that Company does not endorse any of the products or services listed on such site.</p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">22. 	Information or Complaints.</h4> 
	<p style="font-size: 1.1em;">If you have a question or complaint regarding the Site, please send an e-mail to info-florastor@biocodex.com. You may also contact us by writing to 255 Shoreline Drive Suite 450, Redwood City, CA 94065, or by calling us at (877) 356-7787. Please note that e-mail communications will not necessarily be secure; accordingly you should not include credit card information or other sensitive information in your e-mail correspondence with us. California residents may reach the Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs by mail at 1625 North Market Blvd., Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210. </p>
	<br>
	<h4 style="font-weight: 900; font-size: 1.3em;">23. 	Miscellaneous.</h4> 
	<p style="font-size: 1.1em;">This Agreement does not, and shall not be construed to, create any partnership, joint venture, employer-employee, agency or franchisor-franchisee relationship between you and Company. If any provision of this Agreement is found to be unlawful, void or for any reason unenforceable, that provision will be deemed severable from this Agreement and will not affect the validity and enforceability of any remaining provision. You may not assign, transfer or sublicense any or all of your rights or obligations under this Agreement without our express prior written consent. We may assign, transfer or sublicense any or all of our rights or obligations under this Agreement without restriction. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.  No waiver by either party of any breach or default under this Agreement will be deemed to be a waiver of any preceding or subsequent breach or default. Any heading, caption or section title contained herein is for convenience only, and in no way defines or explains any section or provision. All terms defined in the singular shall have the same meanings when used in the plural, where appropriate and unless otherwise specified. Any use of the term “including” or variations thereof in this Agreement shall be construed as if followed by the phrase “without limitation.” This Agreement, including any terms and conditions incorporated herein, is the entire agreement between you and Company relating to the subject matter hereof, and supersedes any and all prior or contemporaneous written or oral agreements or understandings between you and Company relating to such subject matter. Notices to you (including notices of changes to this Agreement) may be made via posting to the Site or by e-mail (including in each case via links), or by regular mail. Without limitation, a printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this Agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. Company will not be responsible for any failure to fulfill any obligation due to any cause beyond its control. It is the express wish of the parties that this Agreement and all related documents be drawn up in English. C'est la volonté expresse des parties que la présente convention ainsi que tous les documents qui s'y rattachent soient rédigés en anglais.</p>
	<br>
	<p style="font-size: 1.1em;">Site © 2017 Biocodex, Inc. unless otherwise noted. All rights reserved.</p>

</div><!-- Page Content -->
</div>



<?php get_footer(); ?>
